// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:dunno/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ColorPaletteModelAdapter());
    registerAdapter(ConfettiAmountAdapter());
    registerAdapter(DunnoStatsModelAdapter());
    registerAdapter(SimpleColorAdapter());
    registerAdapter(SpinnerModelAdapter());
    registerAdapter(SpinnerSegmentModelAdapter());
    registerAdapter(ThemeModeAdapter());
    registerAdapter(UserPreferencesModelAdapter());
    registerAdapter(UserStatsModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ColorPaletteModelAdapter());
    registerAdapter(ConfettiAmountAdapter());
    registerAdapter(DunnoStatsModelAdapter());
    registerAdapter(SimpleColorAdapter());
    registerAdapter(SpinnerModelAdapter());
    registerAdapter(SpinnerSegmentModelAdapter());
    registerAdapter(ThemeModeAdapter());
    registerAdapter(UserPreferencesModelAdapter());
    registerAdapter(UserStatsModelAdapter());
  }
}
